### ISSUE TITLE
Ubuntu 22.04.1 LTS libwebp.so.6 issue with pre-canned binaries

### ISSUE THREAD

**Issue by mattgodbolt** [tidbyt/pixlet#377]
Updating an Ubuntu machine to 22.04 leads to issues:

```sh
$ ./pixlet
./pixlet: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory
$ ldd pixlet 
	linux-vdso.so.1 (0x00007ffe4f93f000)
	libwebpdemux.so.2 => /lib/x86_64-linux-gnu/libwebpdemux.so.2 (0x00007f7f780b2000)
	libwebpmux.so.3 => /lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007f7f780a5000)
	libwebp.so.6 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f780a0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f77e78000)
	libwebp.so.7 => /lib/x86_64-linux-gnu/libwebp.so.7 (0x00007f7f77e0a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f77d23000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7f780ca000)
$ ls /lib/x86_64-linux-gnu/libweb*
/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37        /lib/x86_64-linux-gnu/libwebpmux.so.3      /lib/x86_64-linux-gnu/libwebrtc_audio_processing.so.1
/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37.56.10  /lib/x86_64-linux-gnu/libwebpmux.so.3.0.8  /lib/x86_64-linux-gnu/libwebrtc_audio_processing.so.1.0.0
/lib/x86_64-linux-gnu/libwebpdemux.so.2              /lib/x86_64-linux-gnu/libwebp.so.7
/lib/x86_64-linux-gnu/libwebpdemux.so.2.0.9          /lib/x86_64-linux-gnu/libwebp.so.7.1.3
```

Looks like Ubuntu are now on libwebp 7

**Comment by mattgodbolt** [comment]
Related: #187

**Comment by mattgodbolt** [comment]
Building from source fixes this issue. I'm happy to upload a Ubuntu 22.04-compatible built pixlet if it's useful to anyone here.

**Comment by theaswanson** [comment]
Had this same issue today when attempting to run on Ubuntu 22.04.1 LTS on Windows. Also solved by building from source

**Comment by nbgibson** [comment]
*Mostly solved by building from source. I'm wondering if the issues see in #378 are rooted in the errors seen here and the build/make process is either including the libraries improperly or is just bypassing the error somehow.

**Comment by Jonesie** [comment]
Im using Pop OS 22.04 and have the same blank page issue.  Compiled the source myself. I only have libwebp7 and libwebp-dev on my system.  Do I need to build differently?  If I try to run the binary from the release it tells me libwebp 6 is missing so I guess my build is using 7.

**Comment by Jonesie** [comment]
> Im using Pop OS 22.04 and have the same blank page issue. Compiled the source myself. I only have libwebp7 and libwebp-dev on my system. Do I need to build differently? If I try to run the binary from the release it tells me libwebp 6 is missing so I guess my build is using 7.

Fixed it! Just needed to npm run build before make.  Must have missed that the first time.

**Comment by nbgibson** [comment]
@mattgodbolt Is the issue persisting with the version released today? I've pulled it down to WSL and have things working as expected now. Will be testing in a Ubuntu VM shortly.

**Comment by nbgibson** [comment]
Ok, for a fresh Ubuntu 20.04.5 VM pixlet needs libwebp-dev installed to function, but with the current binary you can just install it via apt and everything appears to function as expected.

**Comment by betterengineering** [comment]
Hey folks! So sorry for the delay on this issue. This should be resolved as of [v0.22.4](https://github.com/tidbyt/pixlet/releases/tag/v0.22.4) since we have resolved the issue where Linux binaries were not being statically linked. See the comment on #187 for more details.
